# Generated by Django 4.2.6 on 2023-10-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Cloth', 'Cloth'), ('Salary', 'Salary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Cloth', 'Cloth'), ('Salary', 'Salary')], max_length=50),
        ),
    ]
