# Generated by Django 4.2.6 on 2023-10-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0005_transaction_remove_income_user_delete_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expenses', 'Expenses')], max_length=50),
        ),
    ]
